add copy method

diff --git a/pxed-run b/pxed-run
--- a/pxed-run
+++ b/pxed-run
@@ -18,6 +18,10 @@ export PATH="${HERE}"/usr/bin/:"${HERE}"/usr/sbin/:"${HERE}"/usr/games/:"${HERE}
 export LD_LIBRARY_PATH="${HERE}"/usr/lib/:"${HERE}"/usr/lib/i386-linux-gnu/:"${HERE}"/usr/lib/x86_64-linux-gnu/:"${HERE}"/usr/lib32/:"${HERE}"/usr/lib64/:"${HERE}"/lib/:"${HERE}"/lib/i386-linux-gnu/:"${HERE}"/lib/x86_64-linux-gnu/:"${HERE}"/lib32/:"${HERE}"/lib64/:"${LD_LIBRARY_PATH}"
 export XDG_DATA_DIRS="${HERE}"/usr/share/:"${XDG_DATA_DIRS}"
 
+uncompress=0
+copy=0
+tftproot=${tftproot:="/srv/tftp"}
+
 trap exit SIGINT SIGTERM ERR
 
 printline(){ echo "[$(/bin/date +"%b %d %H:%M:%S")] $1"; }
@@ -33,6 +37,7 @@ is_arg_valid(){
     fi
     echo $2
 }
+
 
 header(){
 cat << EOL
@@ -50,7 +55,7 @@ dnsmasq: $(<"$HERE/dnsmasq-VERSION")
 fswatch: $(<"$HERE/fswatch-VERSION")
 
 $appname: <opt> <arg>
- -i --iface*           used interface, E.g eth0
+ -i --iface           used interface, E.g eth0
  -a --listen-address   listen on IP address, E.g 10.10.10.1
  -F --dhcp-range       DHCP offer range with lease time, E.g 10.10.10.2-10.10.10.100,24h, default --interface CIDR
  -T --tftp-root        TFTP root dir location, default /srv/tftp
@@ -82,7 +87,12 @@ fisrtsync(){
     local src=$(ls -1r $watch|head -n 1)
 
     printline "fswatch: syncing to $tftproot $src"
-    cat $src | sudo -u $SUDO_USER tar -xf - -C $tftproot
+    if ! (( $copy )); then 
+        cat $src | sudo -u $SUDO_USER tar -xf - -C $tftproot
+    else
+        sudo -u $SUDO_USER cat $src > $tftproot/$(basename $src)
+    fi
+
     printline "fswatch: syncing returned $?"
 }
 
@@ -97,7 +107,7 @@ watcher(){
     printline "fswatch: watching '$watch', using '$watch_method'"
     ${HERE}/usr/bin/fswatch -r -m $watch_method $dr | while read entry; do
 
-        if [[ -z $watch_on_changed && $uncompress != 1 ]]; then
+        if [[ -z $watch_on_changed && $uncompress != 1 && $copy != 1 ]]; then
             printline "fswatch: changed '$entry', but no action given"
             continue
         fi
@@ -107,7 +117,7 @@ watcher(){
             continue
         fi
 
-        if (( $uncompress == 1 )); then
+        if (( $uncompress )); then
 
             # entry has to match watchraw partially
             if [[ $entry != *${watchraw}* ]]; then
@@ -116,6 +126,15 @@ watcher(){
 
             printline "fswatch: changed '$entry', exec tar -xf -C $tftproot"
             cat $entry | sudo -u $SUDO_USER tar -xf - -C $tftproot
+        elif (( $copy )); then
+
+            if [[ $entry != *${watchraw}* ]]; then
+                continue
+            fi
+
+            bn=$(basename $entry)
+            printline "fswatch: changed '$entry', exec cat to $bn"
+            sudo -u $SUDO_USER cat $entry > $tftproot/$bn
         else
             printline "fswatch: changed '$entry', exec '$watch_on_changed'"
             eval $watch_on_changed
@@ -124,6 +143,66 @@ watcher(){
         printline "fswatch: exec returned $?"
     done
 }
+
+main_watcher(){
+
+    if [[ ! -z $watch ]]; then
+    
+        if [[ ! $(command -v fswatch) >/dev/null ]]; then
+            echo "$appname: missing fswatch binary"; exit 1;
+        fi
+    
+        fisrtsync
+        watcher
+    fi
+}
+
+main_pxed(){
+
+    if [[ ! -z $PXED_DEBUG ]]; then
+    	optdel=${opts[@]/--quiet-dhcp}
+    	opts=($optdel --log-dhcp);
+    fi
+
+
+    if [[ -z $dhcprange ]]; then
+    
+        printed=0
+        while true; do
+    
+            ip=$(ip a show $iface 2>/dev/null | awk '/inet\s/ {print $2}')
+            if [[ -z $ip ]]; then
+                if (( $printed != 1)); then
+                    printline "$appname: interface $iface not available. Waiting for $iface"
+                fi
+                printed=1
+                sleep 2
+                continue
+            fi
+    
+            hostmin=$(ipcalc $ip -nb | awk '/HostMin:/ {print $2}')
+            hostmax=$(ipcalc $ip -nb | awk '/HostMax:/ {print $2}')
+    
+            dhcprange="$hostmin,$hostmax,24h"
+            break
+        done
+    fi
+    
+    known_ifaces=$(ls -1 /sys/class/net | sed "/$iface/d" | tr -t '\n' ',')
+    opts+=(--interface=$iface \
+           --except-interface=${known_ifaces::-1} \
+           --dhcp-range=$dhcprange \
+           --enable-tftp=$iface \
+           --tftp-root=$tftproot \
+           --log-facility=$logfile \
+           --dhcp-script="${PXED_DHCP_SCRIPT:=$HERE/etc/pxed-dhcp-hook}" )
+
+    main_watcher &
+
+    printline "$appname: listening on $iface UDP ${listenaddr:="0.0.0.0"}:67:69 with TFTP root $tftproot with $dhcprange"
+    exec -a $appname ${HERE}/usr/sbin/dnsmasq "${opts[@]}" 2>/dev/null
+}
+
 
 opts=(-C ${HERE}/etc/$appname.conf --no-daemon --quiet-dhcp)
 while true; do
@@ -144,6 +223,7 @@ while true; do
     -m| --watch-method) watch_method="$2"; shift 2;; # poll_monitor or inotify_monitor
     -e| --watch-on-changed) watch_on_changed="$2"; shift 2;;
     -u| --uncompress) uncompress=1; shift 1;;
+    -c| --copy) copy=1; shift 1;;
     -v| --version ) echo "$appname: $(<"$HERE/VERSION")"; exit 1;;
     -h| --help ) usage; exit 1 ;;
     * ) break ;;
@@ -154,70 +234,25 @@ if [[ -f $pidfile && -d /proc/$(<$pidfile) ]]; then
     echo "$appname: already running"; exit 1;
 fi
 
-if [[ -z $iface ]]; then
-    echo "$appname: missing mandatory argument --interface"; exit 1;
+mainfunc="pxed"
+if [[ -z  $iface ]]; then
+    if [[ -z $watch ]]; then
+        echo "$appname: missing mandatory argument --interface or --watch"; exit 1;
+    fi
+    mainfunc="watcher"
 fi
 
 header
 
-if [[ ! -z $PXED_DEBUG ]]; then
-	optdel=${opts[@]/--quiet-dhcp}
-	opts=($optdel --log-dhcp);
-fi
-
-tftproot=${tftproot:="/srv/tftp"}
 if [[ ! -d $tftproot ]]; then
     echo "$appname: missing $tftproot directory"; exit 1;
 fi
 
-if [[ ! -z $uncompress  && ! -z $watch_on_changed ]]; then
-    echo "$appname: cant combine --uncompress and --watch-on-changed"; exit 1
+if [[ -z $watch_on_changed ]] && (( $uncompress && $copy )); then
+    echo "$appname: cant combine --uncompress, --watch-on-changed or --copy"; exit 1
 fi
 
 echo $$ > $pidfile
 printline "$appname: PID: $(<$pidfile), logfile: $logfile"
 
-if [[ -z $dhcprange ]]; then
-
-    printed=0
-    while true; do
-
-        ip=$(ip a show $iface 2>/dev/null | awk '/inet\s/ {print $2}')
-        if [[ -z $ip ]]; then
-            if (( $printed != 1)); then
-                printline "$appname: interface $iface not available. Waiting for $iface"
-            fi
-            printed=1
-            sleep 2
-            continue
-        fi
-
-        hostmin=$(ipcalc $ip -nb | awk '/HostMin:/ {print $2}')
-        hostmax=$(ipcalc $ip -nb | awk '/HostMax:/ {print $2}')
-
-        dhcprange="$hostmin,$hostmax,24h"
-        break
-    done
-fi
-
-known_ifaces=$(ls -1 /sys/class/net | sed "/$iface/d" | tr -t '\n' ',')
-opts+=(--interface=$iface \
-       --except-interface=${known_ifaces::-1} \
-       --dhcp-range=$dhcprange \
-       --enable-tftp=$iface \
-       --tftp-root=$tftproot \
-       --log-facility=$logfile \
-       --dhcp-script="${PXED_DHCP_SCRIPT:=$HERE/etc/pxed-dhcp-hook}" )
-
-if [[ ! -z $watch ]]; then
-
-    if [[ ! $(command -v fswatch) >/dev/null ]]; then
-        echo "$appname: missing fswatch binary"; exit 1;
-    fi
-
-    fisrtsync
-    watcher &
-fi
-
-printline "$appname: listening on $iface UDP ${listenaddr:="0.0.0.0"}:67:69 with TFTP root $tftproot with $dhcprange"
-exec -a $appname ${HERE}/usr/sbin/dnsmasq "${opts[@]}" 2>/dev/null
+main_${mainfunc}
